###
GET http://localhost:1234/movies

###
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfafa

### Recuperar todas las peliculas por genero

GET http://localhost:1234/movies?genre=actioN

###  Crear una pelicula

POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/0/60/14417600_max.jpg",
    "genre": [
      "Crime",
      "Drama"
    ]
}
  
### Actualizar pelicula

PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type : application/json

{
  "title": "Hola",
  "year": 1993
}